const cameradata =[{
            "asin": "B097CCXV3G",
            "price": "36852",
            "NumberOfQuestions": "3",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "Canon",
            "ItemWeight": "7.6",
            "Itemmodelnumber": "EOS 2000D",
            "Manufacturer": "ZeeTech",
            "image": "https://m.media-amazon.com/images/I/81p+14yS5jS._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "13",
            "rating": "4.6"
        },
        {
            "asin": "B085J25XYT",
            "price": "46990",
            "NumberOfQuestions": "3",
            "Batteries": "1 Lithium ion batteries required",
            "BestSellersRank": "Digital Point & Shoot Cameras",
            "Brand": "Canon",
            "ItemWeight": "3.09",
            "Itemmodelnumber": "G7XII",
            "Manufacturer": "Pixibytes",
            "image": "https://m.media-amazon.com/images/I/61BVklGh74L._AC_SL1000_.jpg",
            "images" : [],
            "reviewsCount": "55",
            "rating": "4.7"
        },
        {
            "asin": "B08ZYXRCT4",
            "price": "49506",
            "NumberOfQuestions": "0",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "Canon",
            "ItemWeight": "8.48",
            "Itemmodelnumber": "MDCN4000DDC",
            "Manufacturer": "ZeeTech",
            "image": "https://m.media-amazon.com/images/I/91jnyFVhZeL._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "54",
            "rating": "4.5"
        },
        {
            "asin": "B08C68F2DX",
            "price": "288526",
            "NumberOfQuestions": "73",
            "Batteries": "1 Lithium ion batteries required",
            "BestSellersRank": "Mirrorless Cameras",
            "Brand": "Canon",
            "Country of Origin": "Japan",
            "ItemWeight": "1.62",
            "Itemmodelnumber": "4147C002",
            "Manufacturer": "Canon USA",
            "Product Dimensions": "9.1 x 9.1 x 9.1 inches",
            "image": "https://m.media-amazon.com/images/I/81vU-IDxHiL._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "345",
            "rating": "4.9"
        },
        {
            "asin": "B07QBD256Y",
            "price": "51726",
            "NumberOfQuestions": "122",
            "Batteries": "1 Lithium ion batteries required",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "Canon",
            "Country of Origin": "Taiwan",
            "ItemWeight": "2.17",
            "Itemmodelnumber": "3453C002",
            "Manufacturer": "Canon",
            "Product Dimensions": "2.7 x 4.8 x 3.6 inches",
            "image": "https://m.media-amazon.com/images/I/71-YNbmRcDL._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "865",
            "rating": "4.8"
        },
        {
            "asin": "B088KT6C1W",
            "price": "31746",
            "NumberOfQuestions": "6",
            "Batteries": "1 Lithium ion batteries required",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "Canon",
            "ItemWeight": "6.04",
            "Itemmodelnumber": "CN4000DPADV",
            "Manufacturer": "Pixibytes",
            "image": "https://m.media-amazon.com/images/I/519gXp4eODS._AC_.jpg",
            "images" : [],
            "reviewsCount": "154",
            "rating": "4.7"
        },
        {
            "asin": "B07H4SFG4G",
            "price": "36926",
            "NumberOfQuestions": "57",
            "BestSellersRank": "Digital Camera Accessory Kits",
            "Brand": "Canon",
            "Country of Origin": "Taiwan",
            "ItemWeight": "10.8",
            "Itemmodelnumber": "2973C002",
            "Manufacturer": "Canon",
            "Product Dimensions": "2.9 x 2.9 x 2.5 inches",
            "image": "https://m.media-amazon.com/images/I/71XzMjXPO1L._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "527",
            "rating": "4.8"
        },
        {
            "asin": "B08BVT9CK2",
            "price": "184926",
            "NumberOfQuestions": "57",
            "Batteries": "1 Lithium ion batteries required",
            "BestSellersRank": "Mirrorless Cameras",
            "Brand": "Canon",
            "Country of Origin": "Japan",
            "ItemWeight": "1.5",
            "Itemmodelnumber": "4082C002",
            "Manufacturer": "Canon USA",
            "Product Dimensions": "3.48 x 5.45 x 3.84 inches",
            "image": "https://m.media-amazon.com/images/I/81HwzslD2oL._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "561",
            "rating": "4.8"
        },
        {
            "asin": "B0101RW3QK",
            "price": "48100",
            "NumberOfQuestions": "93",
            "Batteries": "1 Lithium ion batteries required",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "Canon",
            "ItemWeight": "3",
            "Itemmodelnumber": "2727C021",
            "Manufacturer": "Canon",
            "Product Dimensions": "3.1 x 5.1 x 4 inches",
            "image": "https://m.media-amazon.com/images/I/71W1KvLH3sL._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "956",
            "rating": "4.8"
        },
        {
            "asin": "B07C2Z21X5",
            "price": "33300",
            "NumberOfQuestions": "147",
            "Batteries": "1 Lithium ion batteries required",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "Canon",
            "Country of Origin": "Taiwan",
            "ItemWeight": "1.04",
            "Itemmodelnumber": "2727C002",
            "Manufacturer": "Canon",
            "Product Dimensions": "3.1 x 5.1 x 4 inches",
            "image": "https://m.media-amazon.com/images/I/71EWRyqzw0L._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "1,146",
            "rating": "4.8"
        },
        {
            "asin": "B08KSMKHF3",
            "price": "36186",
            "NumberOfQuestions": "67",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "Canon",
            "ItemWeight": "15.4",
            "Itemmodelnumber": "Canon EOS 4000D",
            "Manufacturer": "Canon intl",
            "Product Dimensions": "5.08 x 3.04 x 3.99 inches",
            "image": "https://m.media-amazon.com/images/I/919yB90BcSL._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "892",
            "rating": "4.6"
        },
        {
            "asin": "B08K7CKKB1",
            "price": "37666",
            "NumberOfQuestions": "41",
            "Batteries": "2 Lithium ion batteries required",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "Canon",
            "ItemWeight": "1.05",
            "Itemmodelnumber": "Canon EOS 2000d",
            "Manufacturer": "Canon Intl",
            "Product Dimensions": "3.99 x 3.06 x 3.99 inches",
            "image": "https://m.media-amazon.com/images/I/91btQgPuWIL._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "384",
            "rating": "4.7"
        },
        {
            "asin": "B08KSKV35C",
            "price": "51726",
            "NumberOfQuestions": "39",
            "Batteries": "1 Lithium ion batteries required",
            "BestSellersRank": "Mirrorless Cameras",
            "Brand": "Canon",
            "Country of Origin": "Japan",
            "ItemWeight": "2.05",
            "Itemmodelnumber": "4728C006",
            "Manufacturer": "Canon USA",
            "Product Dimensions": "7.2 x 7.3 x 5.2 inches",
            "image": "https://m.media-amazon.com/images/I/71yvRxkCIuL._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "362",
            "rating": "4.8"
        },
        {
            "asin": "B07P15K8Q7",
            "price": "44326",
            "NumberOfQuestions": "193",
            "Batteries": "2 Lithium ion batteries required",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "Canon",
            "ItemWeight": "7.41",
            "Itemmodelnumber": "Canon T7",
            "Manufacturer": "Canon",
            "Product Dimensions": "5.09 x 3.99 x 3.06 inches",
            "image": "https://m.media-amazon.com/images/I/71owuc65uYL._AC_SL1024_.jpg",
            "images" : [],
            "reviewsCount": "2,155",
            "rating": "4.8"
        },
        {
            "asin": "B07H484HLT",
            "price": "133126",
            "NumberOfQuestions": "207",
            "Batteries": "1 Lithium ion batteries required",
            "BestSellersRank": "Mirrorless Cameras",
            "Brand": "Canon",
            "Country of Origin": "Malaysia",
            "ItemWeight": "1.46",
            "Itemmodelnumber": "3075C002",
            "Manufacturer": "Canon",
            "Product Dimensions": "3.3 x 5.3 x 3.9 inches",
            "image": "https://m.media-amazon.com/images/I/81LHdyZj27L._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "539",
            "rating": "4.8"
        },
        {
            "asin": "B089X8L7BW",
            "price": "29526",
            "NumberOfQuestions": "0",
            "Batteries": "1 Lithium ion batteries required",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "Canon",
            "ItemWeight": "3",
            "Itemmodelnumber": "CN4000D",
            "Manufacturer": "Pixibytes",
            "image": "https://m.media-amazon.com/images/I/713LgUnCDIL._AC_SL1000_.jpg",
            "images" : [],
            "reviewsCount": "1",
            "rating": "5"
        },
        {
            "asin": "B086TTTZR5",
            "price": "96126",
            "NumberOfQuestions": "134",
            "Batteries": "1 Lithium ion batteries required",
            "BestSellersRank": "Mirrorless Cameras",
            "Brand": "Canon",
            "Country of Origin": "USA",
            "ItemWeight": "3.91",
            "Itemmodelnumber": "3380C132",
            "Manufacturer": "Canon USA",
            "Product Dimensions": "3.02 x 3.02 x 3.5 inches",
            "image": "https://m.media-amazon.com/images/I/811+58GXGOL._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "679",
            "rating": "4.7"
        },
        {
            "asin": "B079Y6T7T6",
            "price": "42846",
            "NumberOfQuestions": "468",
            "Batteries": "1 Lithium ion batteries required",
            "BestSellersRank": "Mirrorless Cameras",
            "Brand": "Canon",
            "ItemWeight": "13.8",
            "Itemmodelnumber": "2680C001",
            "Manufacturer": "Canon",
            "Product Dimensions": "2.3 x 4.6 x 3.5 inches",
            "image": "https://m.media-amazon.com/images/I/81HywbzL4ZL._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "3,066",
            "rating": "4.8"
        },
        {
            "asin": "B09BX7NCFG",
            "price": "0",
            "NumberOfQuestions": "0",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "Canon",
            "Manufacturer": "Canon Intl.",
            "image": "https://m.media-amazon.com/images/I/51hosDzOuSL._AC_.jpg",
            "images" : []
        },
        {
            "asin": "B00007GQLU",
            "price": "31006",
            "NumberOfQuestions": "412",
            "BestSellersRank": "SLR Camera Lenses",
            "Brand": "Canon",
            "Country of Origin": "Japan",
            "ItemWeight": "15",
            "Itemmodelnumber": "2519A012",
            "Manufacturer": "Canon",
            "Product Dimensions": "2.83 x 2.95 x 2.95 inches",
            "image": "https://m.media-amazon.com/images/I/81XPZ7sQqsL._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "1,936",
            "rating": "4.8"
        },
        {
            "asin": "B01LXTX4WY",
            "price": "40626",
            "NumberOfQuestions": "141",
            "BestSellersRank": "SLR Camera Lenses",
            "Brand": "Canon",
            "Country of Origin": "Malaysia",
            "ItemWeight": "1.56",
            "Itemmodelnumber": "0571C005",
            "Manufacturer": "Canon",
            "Product Dimensions": "5.7 x 5.7 x 5.7 inches",
            "image": "https://m.media-amazon.com/images/I/71xJWYqc7mL._AC_SL1500_.jpg",
            "images" : [],
            "reviewsCount": "403",
            "rating": "4.7"
        },
        {
            "asin": "B00F87A7W6",
            "price": "6,590.00",
            "Batteries": "‎1 Lithium Metal batteries required.",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "‎Commlite",
            "Country of Origin": "‎China",
            "ItemWeight": "1.01",
            "Itemmodelnumber": "‎CM-EF-NEX",
            "Manufacturer": "‎Commlite",
            "Product Dimensions": "12.4 x 11.2 x 5.6 Centimeters",
            "reviewsCount": "74",
            "rating": "3.6"
        },
        {
            "asin": "B00XOXFB1I",
            "price": "53,990.00",
            "Batteries": "‎1 Lithium Metal batteries required.",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "‎Sony",
            "Country of Origin": "‎Thailand",
            "Itemmodelnumber": "‎ILCE-6000Y",
            "Manufacturer": "‎Sony Imaging Products & Solutions Inc.",
            "Product Dimensions": "45 x 120 x 67 Millimeters",
            "reviewsCount": "605",
            "rating": "4.5"
        },
        {
            "asin": "B07RJWB548",
            "price": "52,890.00",
            "Batteries": "‎1 D batteries required.",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "‎Canon",
            "Country of Origin": "‎Taiwan",
            "ItemWeight": "2.68",
            "Itemmodelnumber": "‎EOS 200D II",
            "Manufacturer": "‎Canon Inc.",
            "Product Dimensions": "22 x 17 x 14 Centimeters",
            "reviewsCount": "854",
            "rating": "4.4"
        },
        {
            "asin": "B01N6H41JP",
            "price": "52,032.00",
            "Batteries": "‎1 D batteries required.",
            "BestSellersRank": "DSLR Cameras",
            "Brand": "‎Nikon",
            "ItemWeight": "1.02",
            "Itemmodelnumber": "‎D5600",
            "Manufacturer": "‎Nikon Corporation",
            "Product Dimensions": "7 x 12.4 x 9.7 Centimeters",
            "reviewsCount": "1,852",
            "rating": "4.5"
        },
        {
            "asin": "B06Y5RTN1T",
            "price": "87,850.00",
            "Brand": "‎Nikon",
            "Country of Origin": "‎China",
            "ItemWeight": "1.05",
            "Itemmodelnumber": "‎D7500 18-140mm",
            "Manufacturer": "‎Nikon Corporation",
            "Product Dimensions": "31.8 x 15.2 x 21.6 Centimeters",
            "reviewsCount": "255",
            "rating": "4.3"
        }
];

export default cameradata;