const Chocolatedata = [
        {
            "asin": "B071X6KY1W",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "102",
            "breadCrumbs": "Grocery & Gourmet Foods›Sweets, Chocolate & Gum›Chocolate›Bars",
            "delivery": "",
            "desc": "Style Name:Fruit & Nut\n\n\n\n\n\n | \n\nSize:137 g (Pack of 3)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nCadbury Dairy Milk Silk is all about regaling in the chocolate's richness and creaminess. The classic taste of Cadbury chocolates enriched with the real goodness of cashews, raisins and apricots, offers you the reason to celebrate every small and big occasion of happiness. In short, Indulge in a rich, smooth and creamy celebration. Contains 3 packs of Cadbury Dairy Milk Silk fruit and nut chocolate bar 137 gm each.",
            "ASIN": "B071X6KY1W",
            "BestSellersRank": "#825 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#10 in Chocolate Bars",
            "Brand": "‎Cadbury",
            "CountryOfOrigin": "‎India",
            "CustomerReviews": "4.4 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4,603 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.4 out of 5 rating",
            "DateFirstAvailable": "13 June 2017",
            "Form": "‎Bar",
            "GenericName": "Chocolates",
            "IncludedComponents": "Cadbury Dairy Milk Silk Fruit and Nut Chocolate Bar, 137g (Pack of 3)",
            "IngredientType": "‎Vegetarian",
            "ItemDimensions ": "21.1 x 7.4 x 4.2 Centimeters",
            "ItemWeight": "411 g",
            "Itempartnumber": "‎7101363296741",
            "Manufacturer": "Mondelez India Foods Pvt. Ltd., Mondelez India Foods Private Limited, Unit No. 2001, 20th Floor, Tower - 3 (Wing C), Indiabulls Finance Centre, Parel Mumbai - 400 013, Phone - 1800227080/Email-Suggestions@mdlzindia.com",
            "NetQuantity": "‎411.0 gram",
            "PackageInformation": "‎Pouch",
            "Price":"120",
            "ProductDimensions": "‎21.1 x 7.4 x 4.2 cm; 411 Grams",
            "Specialty": "‎Vegetarian",
            "Weight": "‎411 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nDiscover Cadbury's deliciously creamy milk chocolate bar with raisins, cashews and apricot.\n\n\n\n\nPlump raisins and chunky almonds are the source of all our fruity nuttiness.\n\n\n\n\nIt stands for goodness. A moment of pure magic!\n\n\n\n\nContains 3 packs of Cadbury Dairy Milk Silk fruit and nut chocolate bar 137 gm each\n\n\n\n\nCountryOfOrigin: India",
            "image": "https://m.media-amazon.com/images/I/61gXOGuTd+S._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/61gXOGuTd+S._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61J1YKs9ocL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71JnArtIjUS._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71XRm0QJEyL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61upKsr84BL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61zSCWvtV9L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71d7jMjr++L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/41PVAWNEkEL.jpg"}],
            "reviewsCount": "4,603 ratings",
            "rating": "4.4",
            "itemDetailUrl": "https://www.amazon.in/dp/B071X6KY1W",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B071X6KY1W",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nCadbury Dairy Milk Silk Fruit and Nut Chocolate Bar, 137g (Pack of 3)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B083LJGP9M",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "107",
            "breadCrumbs": "Grocery & Gourmet Foods›Snack Foods›Biscuits & Cookies",
            "delivery": "",
            "desc": "Design:Choco Fills\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nExperience heavenly bliss with Sunfeast dark fantasy choco fills. Each cookie is made with a perfectly baked caramelized crust that enrobes rich, velvety choco creme, so each bite is a unique combination of crunch and soft, oozing, molten choco creme. Combination of luscious chocolate filling. Enrobed within a perfectly baked rich cookie outer. Epitomizes the brand promise of pure indulgence.",
            "ASIN": "B083LJGP9M",
            "BestSellersRank": "#175 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#1 in Trail Mix\n\n\n#10 in Noodles\n\n\n#17 in Cookies",
            "Brand": "‎Sunfeast",
            "CountryOfOrigin": "‎India",
            "CustomerReviews": "4.5 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n13,862 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.5 out of 5 rating",
            "DateFirstAvailable": "7 January 2020",
            "GenericName": "Dark Fantasy Choco Fills",
            "IngredientType": "‎Vegetarian",
            "Ingredients": "‎Choco Crème (38%), [Sugar, Refined Palm Oil, Refined Palmolein, Coco Solids, Anitioxidant (INS 322(i)) and Contains Added Flavour(s) (Nature Identical Flavouring Substances- Chocolate and Artificial Flavouring Substances- Ethyl Vanilla)], Wheat flour, Hydrogenated Vegetable Oil, Sugar, Invert Syrup, Liquid Glucose, Raising Agents (INS 503(ii), INS 500(ii), INS 450(i)), Cocoa Solids (0.7%), Butter, Milk Solids, Ediblie Common Salt and Emulsifiers (INS 322(i), INS 471).",
            "Item Package Quantity": "‎1",
            "ItemWeight": "600 g",
            "Itempartnumber": "‎8901725110833_FBA",
            "Manufacturer": "ITC",
            "NetQuantity": "‎600.0 gram",
            "Package Dimensions": "‎23.3 x 15.9 x 9.7 cm; 600 Grams",
            "PackageInformation": "‎Box",
            "Price":"60",
            "Specialty": "‎Suitable for vegetarians",
            "Weight": "‎600 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nEpitomizes the brand promise of pure indulgence\n\n\n\n\nEnrobed within a perfectly baked rich cookie outer\n\n\n\n\nCombination of luscious chocolate filling",
            "image": "https://m.media-amazon.com/images/I/81nvWgzLWEL._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/81nvWgzLWEL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/91mIQO1LKwL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/91l0wfey6LL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/91ELdriKewL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/811fnA1K67L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/81BRtoqxajL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/81rLLr+LkhL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/81qzk+HKCQL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/81pntwJpZQL._SL1500_.jpg"}],
            "reviewsCount": "13,862 ratings",
            "rating": "4.5",
            "itemDetailUrl": "https://www.amazon.in/dp/B083LJGP9M",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B083LJGP9M",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\nSave upto 10% on auto-deliveries\n\nChoose how often it's delivered\n\nSkip or cancel any time\n\nSave upto 10% on auto-deliveries\n\nChoose how often it's delivered\n\nSkip or cancel any time\n\n\n\n\n\n\n\n\n\nSunfeast Dark Fantasy Choco Fills, 600 g\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B09B1TPBQK",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "0",
            "breadCrumbs": "Grocery & Gourmet Foods›Sweets, Chocolate & Gum›Chocolate›Packets & Boxes",
            "delivery": "",
            "desc": "Why this Gift Pack? Sweets are meant to be an inevitable part of every special occasion, but premium chocolates add a special touch to any occasion. Snickers Chocolate Gift Pack is all you need to make any celebration bright, fun, and full of sweetness. These treats will make a perfect gift for the chocolate lovers in your life. Hurry up and awake the chocolate fanatic in you! What makes it different? The gift hamper is full of sweet surprises. The pack contains 2 Snickers Peanut, 2 Snickers Peanut Sticks, 2 Snickers Butterscotch Sticks, 1 Snickers Almond & 1 Snickers Almond Stick. Don’t sacrifice taste for nutrition, gift it to your loved ones & watch them rejoice in these delicious chocolate treats. When to gift Snickers Premium Treats? Gift Premium Treats to add a sweet touch to any occasion. Snickers Premium Treats can be gifted to friends, relatives, colleagues, kids, teachers and other dear ones to strengthen the bond and make any celebration extra special. Altogether curated with love, this deliciously rich chocolate gift pack is perfect to spread love. Gift to anyone who loves the premium taste of chocolates or to make someone feel special.",
            "ASIN": "B09B1TPBQK",
            "BestSellersRank": "#7,910 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#83 in Chocolate Packets & Boxes",
            "Brand": "‎SNICKERS",
            "CountryOfOrigin": "‎India",
            "CustomerReviews": "4.1 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n40 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.1 out of 5 rating",
            "DateFirstAvailable": "22 July 2021",
            "Form": "‎Bar, Sticks",
            "GenericName": "Chocolate",
            "IngredientType": "‎Vegetarian",
            "Ingredients": "‎Snickers° Peanut T3 - Filled Chocolate 14 g x 2 units Ingredients Milk Chocolate coating (40%): Sugar, Milk solids, Cocoa butter, Cocoa solids, Dextrose, Edible vegetable fats <5% (Sal fat, Palm oil), Emulsifier (INS 322), Artificial flavour (Ethyl vanillin); Centre filling (60%): Liquid glucose, Peanuts (16%), Sugar, Hydrogenated Vegetable oil (Palm oil), Milk solids, Iodized salt, Cocoa butter, Cocoa solids, Dextrose, Edible vegetable fats <5% (Sal fat, Palm oil), Artificial flavour (Ethyl vanillin), Emulsifier (INS 322). Snickers° Peanut Stick - Filled Chocolate 22 g x 2 units Ingredients Milk Chocolate coating (38%): Sugar, Milk solids, Cocoa butter, Cocoa solids, Dextrose, Edible vegetable fats <5% (Sal fat, Palm oil), Emulsifier (INS 322), Artificial flavour (Ethyl vanillin); Centre filling (62%): Liquid glucose, Peanuts (20%), Sugar, Hydrogenated vegetable oil (Palm oil), Milk solids. Iodized salt, Cocoa butter, Cocoa solids. Dextrose. Edible vegetable fats <5% (Sal fat, Palm oil), Artificial flavour (Ethyl vanillin). Emulsifier (INS 322). Snickers° Butterscotch Stick - Filled Chocolate 22 g x 2 units Ingredients Milk Chocolate coating (38%): Sugar, Milk solids, Cocoa butter, Cocoa solids, Dextrose, Edible vegetable fats <5% (Sal fat, Palm oil), Emulsifier (INS 322), Artificial flavour (Ethyl vanillin); Centre filling (62%): Liquid glucose, Peanuts (20%), Sugar, Hydrogenated vegetable oil (Palm oil), Milk solids, Iodized salt, Cocoa butter, Cocoa solids, Dextrose. Edible vegetable fats <5% (Sal fat, Palm oil). Nature identical flavour (Butterscotch), Emulsifier (INS 322), Artificial flavour (Ethyl vanillin). Snickers® Almond T3 - Filled Chocolate 14 g x 1 unit Ingredients Milk Chocolate coating (45%): Sugar. Milk solids, Cocoa butter, Cocoa solids. Dextrose. Edible vegetable fats <5% (Sal fat, Palm oil). Emulsifier (INS 322), Artificial flavour (Ethyl vanillin); Centre filling (55%): Liquid glucose, Almonds (16%), Sugar, Hydrogenated vegetable oil (Palm oil), Milk solids. Iodized salt, Cocoa butter, Cocoa solids, Dextrose, Edible vegetable fats <5% (Sal fat, Palm oil), Artificial flavour (Ethyl vanillin), Emulsifier (INS 322). Snickers® Almond Stick - Filled Chocolate 22 g x 1 unit Ingredients: Milk Chocolate coating (40%): Sugar, Milk solids, Cocoa butter, Cocoa solids, Dextrose, Edible vegetable fats <5% (Sal fat. Palm oil), Emulsifier (INS 322), Artificial flavour (Ethyl vanillin); Centre filling (60%): Liquid glucose, Almonds (17%), Sugar. Hydrogenated vegetable oil (Palm oil). Milk solids, Iodized salt. Cocoa butter, Cocoa solids, Dextrose, Edible vegetable fats <5% (Sal fat, Palm oil), Artificial flavour (Ethyl vanillin), Emulsifier (INS 322).",
            "ItemDimensions ": "35.5 x 24.9 x 2.3 Centimeters",
            "ItemWeight": "304 g",
            "Manufacturer": "Mars International India Pvt Ltd, Mars International India Pvt Ltd, At Plot No I-09/11A, Khed City Industrial Area, At PO Nimgaon, Taluka khed, District Pune -",
            "NetQuantity": "‎304.0 gram",
            "Packer": "Ameya Plastics, Gate no 261/5 & 261/6, Somwanshi Industrial Estate, At Post Chakan,Village Kharabwadi, Taluka Khed, Dist Pune, Maharashtra",
            "Price":"120",
            "ProductDimensions": "‎35.5 x 24.9 x 2.3 cm; 304 Grams",
            "Specialty": "‎Suitable for Vegetarians",
            "Weight": "‎304 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nPACK CONTENT: Each pack contains 2 snickers peanut 2 snickers peanut sticks 2 snickers butterscotch sticks 1 snickers almond and 1 snickers almond stick\n\n\n\n\nIDEAL CHOCOLATE GIFT PACK: Add sweetness to any occasion with Snickers Gift Pack\n\n\n\n\nNUTTY SNICKERS BARS: Satisfy your taste buds with crunchy peanuts almonds and butterscotch along with soft nougat and caramel\n\n\n\n\nCountryOfOrigin: India\n\n\n\n\nORDER PREMIUM CHOCOLATES ONLINE: Order chocolate gift for home or deliver to your loved ones\n\n\n\n\nCLEAN & ETHICALLY SOURCED INGREDIENTS: We continue to live our purpose which is better moments make the world smile\n\n\n\n\nCOMMONLY SEARCHED TOPICS: best gift gifts chocolate gift chocolates gift pack premium chocolates chocolate gift packs",
            "image": "https://m.media-amazon.com/images/I/61LUPLjFX7L._SL1000_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/61LUPLjFX7L._SL1000_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71V7FdRagiL._SL1000_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71t3xiv-TUL._SL1000_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71LXr-qvu6L._SL1000_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71cek9JSlyL._SL1000_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71YcAOw+aXL._SL1000_.jpg"},
            {image: "https://m.media-amazon.com/images/I/81HBsF4ZsML._SL1500_.jpg"}],
            "reviewsCount": "40 ratings",
            "rating": "4.1",
            "itemDetailUrl": "https://www.amazon.in/dp/B09B1TPBQK",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B09B1TPBQK",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nSnickers Premium Chocolates Gift Pack, 304g (152g x 2 Pack)\n\n\n\n\n\n\n\n\n\n\n\n\n\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B07H6JRFGR",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "4",
            "breadCrumbs": "Grocery & Gourmet Foods›Sweets, Chocolate & Gum›Chocolate›Packets & Boxes",
            "delivery": "",
            "desc": "A delicious indulgent combination of chocolate, caramel and nougat. Longer-lasting chewy multi textured chocolate eat experience.",
            "ASIN": "B07H6JRFGR",
            "BestSellersRank": "#913 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#8 in Chocolate Packets & Boxes",
            "Brand": "‎Cadbury",
            "CountryOfOrigin": "‎India",
            "CustomerReviews": "4.6 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n410 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.6 out of 5 rating",
            "DateFirstAvailable": "28 August 2018",
            "Form": "‎Bar",
            "GenericName": "5 Star Chocolate Home Treats Pack",
            "IngredientType": "‎Vegetarian",
            "ItemDimensions ": "52.1 x 40.6 x 20.3 Centimeters",
            "Item Package Quantity": "‎1",
            "ItemWeight": "202 g",
            "Itempartnumber": "‎30968_FBA",
            "Manufacturer": "Mondelez",
            "NetQuantity": "‎1 count",
            "PackageInformation": "‎Pouch",
            "Price":"100",
            "ProductDimensions": "‎52.1 x 40.6 x 20.3 cm; 202 Grams",
            "Specialty": "‎Suitable for vegeterians",
            "Weight": "‎202 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nA delicious indulgent combination of chocolate, caramel and nougat\n\n\n\n\nLong-lasting yummy chocolatey experience\n\n\n\n\nCountryOfOrigin: India",
            "image": "https://m.media-amazon.com/images/I/71oNj2AEE9L._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/71oNj2AEE9L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61Z+fQaItRS._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71DFlALttHL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/8189rpkfyUS._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/613z5vUQrxL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71uJy3ghboL._SL1500_.jpg"}],
            "reviewsCount": "410 ratings",
            "rating": "4.6",
            "itemDetailUrl": "https://www.amazon.in/dp/B07H6JRFGR",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B07H6JRFGR",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nCadbury 5 Star Chocolate Home Treats Pack, 202 g\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B08X1XR72D",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "0",
            "breadCrumbs": "Grocery & Gourmet Foods›Dried Fruits, Nuts & Seeds›Dried Fruits›Berries›Cranberries",
            "delivery": "",
            "ASIN": "B08X1XR72D",
            "BestSellersRank": "#9,622 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#38 in Dried Cranberries",
            "Brand": "‎True Elements",
            "CustomerReviews": "4.2 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n24 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.2 out of 5 rating",
            "DateFirstAvailable": "19 February 2021",
            "Form": "‎Dried",
            "GenericName": "Mixed berries",
            "IngredientType": "‎Vegetarian",
            "Ingredients": "‎Dried Cranberries, Dried Blueberries, Sugar, Sunflower Oil",
            "ItemDimensions ": "23 x 16 x 5 Centimeters",
            "ItemWeight": "250 g",
            "Manufacturer": "HW Wellness Solutions Private Limited, HW Wellness Solutions Private Limited",
            "NetQuantity": "‎1 count",
            "Packer": "HW Wellness Solutions Private Limited",
            "Price":"100",
            "ProductDimensions": "‎23 x 16 x 5 cm; 250 Grams",
            "Serving Size": "‎25 Grams",
            "Specialty": "‎Natural",
            "Weight": "‎250 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nBRAIN HEALTH: Cranberries and Blueberries are known to reduce stress and reduce memory decline, thus boosting the brain health.\n\n\n\n\nHEART HEALTH: They help in reducing cholesterol, thus protecting the heart from cardiovascular diseases.\n\n\n\n\nANTIOXIDANTS LOADED: These are highly rich in Antioxidants, hence can be helpful in preventing the risk of Urinary Tract Infections.\n\n\n\n\nHEALTHY SNACK: Since these are rich in vitamins and antioxidants, they can be helpful in boosting the immunity. Blueberries also help to reduce the risk of catching infections.\n\n\n\n\nSKIN HEALTH: Since they are rich in Antioxidants, they help in nurturing the quality of your skin.",
            "image": "https://m.media-amazon.com/images/I/81MGW9mqJUL._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/81MGW9mqJUL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61CL5-T-mWL._SL1007_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61aoBVSQSlL._SL1007_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61pMXJ1tuxL._SL1007_.jpg"},
            {image: "https://m.media-amazon.com/images/I/81gtfmO9+VL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61+p+7Zcw3L._SL1007_.jpg"}],
            "reviewsCount": "24 ratings",
            "rating": "4.2",
            "itemDetailUrl": "https://www.amazon.in/dp/B08X1XR72D",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B08X1XR72D",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nTrue Elements Berries Mix 250g - Mix of Cranberries & Blueberries | Healthy Snack | Berry Mix | Dried Berries\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B09B1TSPMK",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "3",
            "breadCrumbs": "Grocery & Gourmet Foods›Sweets, Chocolate & Gum›Chocolate›Packets & Boxes",
            "delivery": "",
            "desc": "Size:263g\n\n\n\n\n\n | \n\nStyle Name:Pack of 2\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWhy this Gift Pack? Sweets are meant to be an inevitable part of every special occasion, but premium chocolates add a special touch to any occasion. Medley Chocolate Gift Pack is all you need to make any celebration bright, fun, and full of sweetness. These treats will make a perfect gift for the chocolate lovers in your life. Hurry up and awake the chocolate fanatic in you! What makes it different? The gift hamper is full of sweet surprises. Each pack contains 2 Snicker Bars with crunchy Peanuts, 3 Snicker Bars with tasty Butterscotch, 1 Rainbow Skittles Pouch and 1 Bounty Bar with the temptation of coconut. Don’t sacrifice taste for nutrition, gift it to your loved ones & watch them rejoice in these delicious chocolate treats. When to gift Medley Premium Treats? Gift Premium Treats to add a sweet touch to any occasion. Medley Premium Treats can be gifted to friends, relatives, colleagues, kids, teachers and other dear ones to strengthen the bond and make any celebration extra special. Altogether curated with love, this deliciously rich chocolate gift pack is perfect to spread love. Gift to anyone who loves the premium taste of chocolates or to make someone feel special.",
            "ASIN": "B09B1TSPMK",
            "BestSellersRank": "#15,183 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#149 in Chocolate Packets & Boxes",
            "Brand": "‎Medley",
            "CountryOfOrigin": "‎Netherlands",
            "CustomerReviews": "3.7 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n90 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n3.7 out of 5 rating",
            "DateFirstAvailable": "22 July 2021",
            "Form": "‎Bar",
            "GenericName": "Chocolate",
            "Importer": "Mars International India Pvt Ltd, 4658- A, No 21, Ansari Road, Darya ganj, New Delhi",
            "IngredientType": "‎Vegetarian",
            "Ingredients": "‎Snickers® Peanut T3 - Filled Chocolate 14 g x 5 units Ingredients: Milk Chocolate coating (40%): Sugar, Milk solids, Cocoa butter, Cocoa solids, Dextrose, Edible vegetable fats <5% (Sal fat, Palm oil), Emulsifier (INS 322), Artificial flavour (Ethyl vanillin); Centre filling (60%): Liquid glucose, Peanuts (16%), Sugar, Hydrogenated Vegetable oil (Palm oil), Milk solids, Iodized salt, Cocoa butter, Cocoa solids, Dextrose, Edible vegetable fats <5% (Sal fat, Palm oil), Artificial flavour (Ethyl vanillin), Emulsifier (INS 322). Snickers® Butterscotch Stick - Filled Chocolate 22 g x 3 units Ingredients: Milk Chocolate coating (38%): Sugar, Milk solids, Cocoa butter, Cocoa solids, Dextrose, Edible vegetable fats <5% (Sal fat, Palm oil), Emulsifier (INS 322), Artificial flavour (Ethyl vanillin); Centre filling (62%): Liquid glucose, Peanuts (20%), Sugar, Hydrogenated vegetable oil (Palm oil), Milk solids, Iodized salt, Cocoa butter, Cocoa solids, Dextrose, Edible vegetable fats <5% (Sal fat, Palm oil), Nature identical flavour (Butterscotch), Emulsifier (INS 322), Artificial flavour (Ethyl vanillin). Bounty® Bar - Filled Chocolate 57 g (2 Bars x 28.5 g each) x 1 unit Ingredients Milk chocolate coating (Sugar, Milk solids (Skimmed milk powder, Lactose, Milk fat, Whey powder), Cocoa butter, Cocoa mass, Emulsifier (Soya lecithin (INS 322)), Natural vanilla extract), Centre filling (Desiccated coconut (21%), Sugar, Glucose syrup, Emulsifiers (Mono-and diglycerides of fatty acids (INS 471), Glycerol (INS 422)), Salt, Natural vanilla extract). Milk chocolate: Cocoa solids 25% min. SKITTLES®ORIGINAL 9 g x 1 unit Ingredients Sugar, Liquid glucose, Palm oil, Acidity regulators [INS 330, INS 331(iii)], Stabilizers [INS 1400, INS 1450], Emulsifier [INS 1422], Flavours [Natural, Nature-identical and Artificial (Orange, Strawberry)], Colours [INS 171, INS 102, INS 129, INS 110, INS 132, INS 133], Glazing agent [INS 903].",
            "ItemDimensions ": "33.7 x 24.6 x 2.3 Centimeters",
            "ItemWeight": "263 g",
            "Manufacturer": "Mars Nederland B.V. & Mars Wrigely Confectionary (China) Limited, Mars Nederland B.V., Postbus 81, 5460 AB Veghel",
            "NetQuantity": "‎263.0 gram",
            "Packer": "Ameya Plastics, Gate no 261/5 & 261/6, Somwanshi Industrial Estate, At Post Chakan,Village Kharabwadi, Taluka Khed, Dist Pune, Maharashtra",
            "Price":"160",
            "ProductDimensions": "‎33.7 x 24.6 x 2.3 cm; 263 Grams",
            "Weight": "‎263 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nPACK CONTENT: Each pack contains 2 snickers peanut 3 snickers butterscotch sticks 1 skittles original pouch and 1 bounty bar\n\n\n\n\nIDEAL CHOCOLATE GIFT PACK: Add sweetness to any occasion with Medley Gift Pack\n\n\n\n\nNUTTY SNICKERS BARS: Satisfy your taste buds with crunchy peanuts and butterscotch along with soft nougat and caramel\n\n\n\n\nBITE-SIZED SKITTLES: Fruit candies to add rainbow colours to your moments\n\n\n\n\nBOUNTY PLEASURE: Irresistible coconut delight covered in milk chocolate coating\n\n\n\n\nCountryOfOrigin: Snickers comes from India, bounty from Netherlands while skittles comes from China\n\n\n\n\nORDER ASSORTED CHOCOLATES ONLINE: Order chocolate gift for home or deliver to your loved ones\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nCLEAN & ETHICALLY SOURCED INGREDIENTS: We continue to live our purpose which is better moments make the world smile\n\nCOMMONLY SEARCHED TOPICS: best gift gifts chocolate gift chocolates gift pack premium chocolates chocolate gift packs\n\n\n\nShow More",
            "image": "https://m.media-amazon.com/images/I/61i98ZwVPdS._SL1000_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/61i98ZwVPdS._SL1000_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71EdQpSJaFL._SL1000_.jpg"},
            {image: "https://m.media-amazon.com/images/I/714UZQik4PL._SL1000_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71deLaRWDtL._SL1000_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71S28lVGYBL._SL1000_.jpg"},
            {image: "https://m.media-amazon.com/images/I/812HSMog6uL._SL1500_.jpg"}],
            "reviewsCount": "90 ratings",
            "rating": "3.7",
            "itemDetailUrl": "https://www.amazon.in/dp/B09B1TSPMK",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B09B1TSPMK",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nMedley Premium Chocolates Gift Pack -263g (131.5g x 2 Pack)\n\n\n\n\n\n\n\n\n\n\n\n\n\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B089GX3YXS",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "0",
            "breadCrumbs": "Grocery & Gourmet Foods›Sweets, Chocolate & Gum›Indian Sweets",
            "delivery": "",
            "desc": "Pack of Mysore Pak 200gm + Kaju Katli 200gm",
            "ASIN": "B089GX3YXS",
            "BestSellersRank": "#18,185 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#129 in Indian Sweets",
            "Brand": "‎Lal",
            "CountryOfOrigin": "‎India",
            "CustomerReviews": "4.2 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n98 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.2 out of 5 rating",
            "DateFirstAvailable": "31 May 2020",
            "IngredientType": "‎Vegetarian",
            "ItemWeight": "475 g",
            "Manufacturer": "Lal Sweets Private Limited",
            "NetQuantity": "‎400 gram",
            "Package Dimensions": "‎21.5 x 15 x 5 cm; 475 Grams",
            "Price":"160",
            "Region Produced In": "‎India",
            "Specialty": "‎Suitable for vegetarians",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nMysore Pak 200gm\n\n\n\n\nKaju Katli 200gm\n\n\n\n\nDelicious and tasty",
            "image": "https://m.media-amazon.com/images/I/71GUlM0Q2JL._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/71GUlM0Q2JL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/51bskd31JPL.jpg"},
            {image: "https://m.media-amazon.com/images/I/41UO8hxIaSL._SL1105_.jpg"},
            {image: "https://m.media-amazon.com/images/I/51iSBkXIftL.jpg"},
            {image: "https://m.media-amazon.com/images/I/5188SsWFGDL._SL1200_.jpg"},
            {image: "https://m.media-amazon.com/images/I/51ulfLN12XL._SL1240_.jpg"}],
            "reviewsCount": "98 ratings",
            "rating": "4.2",
            "itemDetailUrl": "https://www.amazon.in/dp/B089GX3YXS",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B089GX3YXS",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nLAL Royal Delight 400g\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B07RZ7RPRD",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "162",
            "breadCrumbs": "Grocery & Gourmet Foods›Jams, Honey & Spreads›Nut Butters",
            "delivery": "",
            "ASIN": "B07RZ7RPRD",
            "Allergen Information": "‎Peanuts",
            "BestSellersRank": "#16 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#2 in Nut Butters",
            "Brand": "‎I LOVE PB",
            "CountryOfOrigin": "‎India",
            "Cuisine": "‎American",
            "CustomerReviews": "4.7 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n22,722 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.7 out of 5 rating",
            "DateFirstAvailable": "16 May 2019",
            "GenericName": "Peanut Butter",
            "Importer": "Xcelerators, 555, Ashok Chowk, Adarsh Nagar,Jaipur 302004, Rajasthan, Contact Number - 9352026568, Contact Email - hello@xcelerators.biz",
            "IncludedComponents": "Pack of 1 of Peanut Butter",
            "IngredientType": "‎Vegetarian",
            "Ingredients": "‎Roasted peanuts, Sugar, salt, permitted stabilizing agent",
            "ItemDimensions ": "15 x 15 x 15 Centimeters",
            "Item Package Quantity": "‎1",
            "ItemWeight": "1 kg 250 g",
            "Itempartnumber": "‎12503",
            "Manufacturer": "MYFITNESS, SuperNutri Foods, Palitana Road, Talaja 364140, Gujarat; +91 8866434363, MYFITNESS, SuperNutri Foods, Palitana Road, Talaja 364140, Gujarat; +91 8866434363",
            "NetQuantity": "‎1250.0 gram",
            "PackageInformation": "‎Jar",
            "Packer": "Xcelerators, 555, Ashok Chowk, Adarsh Nagar,Jaipur 302004, Rajasthan, Contact Number - 9352026568, Contact Email - hello@xcelerators.biz",
            "Price":"550",
            "ProductDimensions": "‎15 x 15 x 15 cm; 1.25 Kilograms",
            "Serving Size": "‎320 gigapascals",
            "Specialty": "‎High Protein, Low Carb, Vegan",
            "Storage Instructions": "‎Keep in a Cool & Dry Place",
            "Volume": "‎4500 Quarts",
            "Weight": "‎1.25 Kilograms",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nPremium chocolate\n\n\n\n\nCountryOfOrigin: India\n\n\n\n\nHigh protein\n\n\n\n\nHalal, Container Type : Tub\n\n\n\n\nRich in taste\n\n\n\n\nLow carbs\n\n\n\n\nOriginal American recipe",
            "image": "https://m.media-amazon.com/images/I/81iMkZXy7iL._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/81iMkZXy7iL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/91pX5rMSMzL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/91WiBFz-l0L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/81sqM+nf-8L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/81JXIJWd6PL._SL1500_.jpg"}],
            "reviewsCount": "22,722 ratings",
            "rating": "4.7",
            "itemDetailUrl": "https://www.amazon.in/dp/B07RZ7RPRD",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B07RZ7RPRD",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\nSave upto 10% on auto-deliveries\n\nChoose how often it's delivered\n\nSkip or cancel any time\n\nSave upto 10% on auto-deliveries\n\nChoose how often it's delivered\n\nSkip or cancel any time\n\n\n\n\n\n\n\n\n\nMYFITNESS Chocolate Peanut Butter Smooth (1250g (Single Unit))\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B08TWSR47Y",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "4",
            "breadCrumbs": "Grocery & Gourmet Foods›Jams, Honey & Spreads›Nut Butters",
            "delivery": "",
            "ASIN": "B08TWSR47Y",
            "BestSellersRank": "#1,020 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#31 in Nut Butters",
            "Brand": "‎I LOVE PB",
            "CountryOfOrigin": "‎India",
            "CustomerReviews": "4.7 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n1,106 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.7 out of 5 rating",
            "DateFirstAvailable": "14 November 2019",
            "GenericName": "PEANUT BUTTER",
            "Importer": "TANVI Fitness Private Limited, 287/288 Landmark Business HUB, Tokarkhada Silvassa Dadra and Nagar Haveli 396230 Phone - 8866434363, E- Mail- care@myfitness.co.in",
            "IngredientType": "‎Vegetarian",
            "Ingredients": "‎Roasted peanuts, Sugar, salt, permitted stabilizing agent,rice crisp",
            "ItemDimensions ": "9 x 9 x 11 Centimeters",
            "ItemWeight": "510 g",
            "Itempartnumber": "‎B07QMJ8XNG",
            "Manufacturer": "SUPERNUTRI FOODS, SUPERNUTRI FOODS, MYFITNESS, SuperNutri Foods, Palitana Road, Talaja 364140, Gujarat; +91 8866434363",
            "NetQuantity": "‎1 count",
            "PackageInformation": "‎Jar",
            "Packer": "TANVI Fitness Private Limited, 287/288 Landmark Business HUB, Tokarkhada Silvassa Dadra and Nagar Haveli 396230 Phone - 8866434363, E- Mail- care@myfitness.co.in",
            "Price":"200",
            "ProductDimensions": "‎9 x 9 x 11 cm; 510 Grams",
            "Serving Size": "‎32 gravity",
            "Specialty": "‎Vegetarian",
            "Weight": "‎510 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nPremium chocolate, Original American recipe, High protein, Low carbs, Rich in taste, Halal, CountryOfOrigin: India\n\n\n\n\nItemWeight: 510.0 grams\n\n\n\n\nSpecialty: Vegetarian\n\n\n\n\nPackage Dimensions: 120.0 L x 120.0 W x 140.0 H (millimeters)",
            "image": "https://m.media-amazon.com/images/I/71Iq7VyAtsL._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/71Iq7VyAtsL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71DoAM-JWpL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/81eZd3QUHpL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71i5hflMZfL._SL1500_.jpg"}],
            "reviewsCount": "1,106 ratings",
            "rating": "4.7",
            "itemDetailUrl": "https://www.amazon.in/dp/B08TWSR47Y",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B08TWSR47Y",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nMYFITNESS Chocolate Peanut Butter Crunchy 510g\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B07MXHXY29",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "0",
            "breadCrumbs": "Grocery & Gourmet Foods›Sweets, Chocolate & Gum›Chocolate›Bars",
            "delivery": "",
            "desc": "Cadbury dairy milk, your favourite chocolate in the perfect family pack for those everyday moments of joy that you want to share with your near and dear ones with something sweet. Just one bite will take you into the world of warmth, happiness and spontaneous fun. Rich, smooth and creamy classic milk chocolate which gives you more joy in every bite.",
            "ASIN": "B07MXHXY29",
            "BestSellersRank": "#1,125 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#18 in Chocolate Bars",
            "Brand": "‎Cadbury",
            "CountryOfOrigin": "‎India",
            "CustomerReviews": "4.5 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n807 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.5 out of 5 rating",
            "DateFirstAvailable": "15 January 2019",
            "Form": "‎Bar",
            "GenericName": "Dairy Milk Chocolate Home Treats Pack",
            "IngredientType": "‎Vegetarian",
            "Ingredients": "‎Sugar, Milk Solids (22%*), Cocoa Butter, Cocoa Solids, Emulsifiers (442, 476). CONTAINS ADDED FLAVOUR (NATURAL, NATURE IDENTICAL AND ARTIFICIAL (ETHYL VANILLIN) FLAVOURING SUBSTANCES). Allergen Information: Contains Milk. Manufactured on equipment that also processes products containing tree nuts and wheat.",
            "ItemDimensions ": "15.2 x 2.5 x 20.3 Centimeters",
            "Item Package Quantity": "‎1",
            "ItemWeight": "126 g",
            "Itempartnumber": "‎34690",
            "Manufacturer": "Mondelez India Foods Pvt. Ltd., Mondelez India Foods Pvt. Ltd.",
            "NetQuantity": "‎126.0 gram",
            "PackageInformation": "‎Pouch",
            "Packer": "Mondelez India Foods Pvt. Ltd.",
            "Price":"200",
            "ProductDimensions": "‎15.2 x 2.5 x 20.3 cm; 126 Grams",
            "Specialty": "‎Vegetarian",
            "Weight": "‎126 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nA bite for each one in the family\n\n\n\n\nCadbury dairy milk chocolate is for those everyday moments of joy that you want to share with your near and dear ones with something sweet\n\n\n\n\nIt stands for goodness a moment of pure magic",
            "image": "https://m.media-amazon.com/images/I/61FcLovf3mL._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/61FcLovf3mL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61In+4xwe8L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71n25yZCwfL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71wZ7GErh+L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71yPQ-sRUpL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71HgjW7QgFL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/612iqDL0FwL._SL1500_.jpg"}],
            "reviewsCount": "807 ratings",
            "rating": "4.5",
            "itemDetailUrl": "https://www.amazon.in/dp/B07MXHXY29",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B07MXHXY29",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nCadbury Dairy Milk Chocolate Home Treats Pack, 126 g\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B08GXK7F6Q",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "12",
            "breadCrumbs": "Grocery & Gourmet Foods›Sweets, Chocolate & Gum›Chocolate›Bars",
            "delivery": "",
            "desc": "Amul dark chocolate is couverture chocolate with minimum 47% cocoa solids and is preferred by home bakers for making Products.",
            "ASIN": "B08GXK7F6Q",
            "BestSellersRank": "#420 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#2 in Chocolate Bars",
            "Brand": "‎Amul",
            "CountryOfOrigin": "‎India",
            "CustomerReviews": "4.6 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n905 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.6 out of 5 rating",
            "DateFirstAvailable": "17 August 2020",
            "Form": "‎Bar",
            "GenericName": "Dark Chocolate",
            "Importer": "Kaira District Co-operative milk producers' Union Ltd.(A Unit of Kaira Dist. Co-op. Milk Producers’ Union Ltd.), Jibhaipura, Nadiad-Ahmedabad Road, Mehmedabad, Dist.: Kheda, Gujarat – 387 130.Lic. No. 10020021005504.",
            "IngredientType": "‎Vegetarian",
            "ItemDimensions ": "21 x 9 x 2 Centimeters",
            "Item Package Quantity": "‎1",
            "ItemWeight": "150 g",
            "Item model number": "‎AAK612",
            "Manufacturer": "GCMMF, Kaira District Co-operative milk producers' Union Ltd.(A Unit of Kaira Dist. Co-op. Milk Producers’ Union Ltd.), Jibhaipura, Nadiad-Ahmedabad Road, Mehmedabad, Dist.: Kheda, Gujarat – 387 130.Lic. No. 10020021005504.",
            "NetQuantity": "‎1 count",
            "Packer": "Kaira District Co-operative milk producers' Union Ltd.(A Unit of Kaira Dist. Co-op. Milk Producers’ Union Ltd.), Jibhaipura, Nadiad-Ahmedabad Road, Mehmedabad, Dist.: Kheda, Gujarat – 387 130.Lic. No. 10020021005504.",
            "Price":"110",
            "ProductDimensions": "‎21 x 9 x 2 cm; 150 Grams",
            "Specialty": "‎Natural",
            "Volume": "‎150 Millilitres",
            "Weight": "‎150 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\n55% dark chocolate\n\n\n\n\nNo milk solids\n\n\n\n\nNo vegetable fat\n\n\n\n\nNatural source of antioxidants",
            "image": "https://m.media-amazon.com/images/I/41XQL-1sVTS.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/41XQL-1sVTS.jpg"},
            {image: "https://m.media-amazon.com/images/I/41DwWD0BWIS.jpg"},
            {image: "https://m.media-amazon.com/images/I/71dMYgPbLoS._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/41XQL-1sVTS.jpg"}],
            "reviewsCount": "905 ratings",
            "rating": "4.6",
            "itemDetailUrl": "https://www.amazon.in/dp/B08GXK7F6Q",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B08GXK7F6Q",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nAmul Dark Chocolate, 150g\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B07W4JS5ZL",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "0",
            "breadCrumbs": "Grocery & Gourmet Foods›Sweets, Chocolate & Gum›Chocolate›Bars",
            "delivery": "",
            "desc": "Amul Chocolate is made from the finest cocoa beans which delivers a robust flavour that is not for the faint hearted. It is100% bliss. Amul Chocolate is truly a chocolate connoisseur delight.",
            "ASIN": "B07W4JS5ZL",
            "Allergen Information": "‎Allergen-Free",
            "BestSellersRank": "#2,030 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#38 in Chocolate Bars",
            "Brand": "‎Amul",
            "CustomerReviews": "4.8 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n5 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.8 out of 5 rating",
            "DateFirstAvailable": "6 August 2019",
            "IngredientType": "‎Vegetarian",
            "ItemWeight": "150 g",
            "Manufacturer": "kAira uNion",
            "Package Dimensions": "‎21 x 10 x 3 cm; 150 Grams",
            "Price":"140",
            "Specialty": "‎Vegetarian",
            "Weight": "‎150 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nA delicious chocolate from the house of Amul\n\n\n\n\nWith goodness of cocoa\n\n\n\n\nConsume directly",
            "image": "https://m.media-amazon.com/images/I/81IBW9geZJL._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/81IBW9geZJL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/91EqeXriEEL._SL1500_.jpg"}],
            "reviewsCount": "5 ratings",
            "rating": "4.8",
            "itemDetailUrl": "https://www.amazon.in/dp/B07W4JS5ZL",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B07W4JS5ZL",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nAMUL SUGARFREE Dark Chocolate 150G Pack of 2\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B071ZKX425",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "0",
            "breadCrumbs": "",
            "delivery": "",
            "desc": "",
            "ASIN": "B071ZKX425",
            "BestSellersRank": "#678 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#13 in Chocolate",
            "Brand": "‎Cadbury",
            "CountryOfOrigin": "‎India",
            "CustomerReviews": "4.4 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4,220 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.4 out of 5 rating",
            "DateFirstAvailable": "26 July 2019",
            "Format": "‎Ball",
            "ItemWeight": "‎202 g",
            "Manufacturer": "Mondelez",
            "NetQuantity": "‎208.8 gram",
            "Package Dimensions": "‎16.6 x 10 x 8.2 cm; 202 Grams",
            "Price":"100",
            "Special Feature": "‎Vegetarian",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nA chocoholic will simply love these chocolate pops which have a crunchy sweet taste\n\n\n\n\nThey are known for their delectable stuffs that often hits our tongue\n\n\n\n\nIt is the most amazing chocolate to fill your day with sweetness",
            "image": "https://m.media-amazon.com/images/I/71M8mGCp21L._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/71M8mGCp21L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71Mn-rGfX3L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61t-vJrxIML._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61g61FGK+GL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/9122cwVbVaL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/91GDpc6WkTL._SL1500_.jpg"}],
            "reviewsCount": "4,220 ratings",
            "rating": "4.4",
            "itemDetailUrl": "https://www.amazon.in/dp/B071ZKX425",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B071ZKX425",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nCadbury Dairy Milk Chocolate Shots, 208.8 gm Carton (58 units x 3.6 gm)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWhat is Amazon Pantry?\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B07FNXXBJB",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "0",
            "breadCrumbs": "Grocery & Gourmet Foods›Sweets, Chocolate & Gum›Chocolate›Bars",
            "delivery": "",
            "desc": "A delicious fusion of crunchy peanuts, sweet caramel and a creamy centre all coated in smooth cadbury milk chocolate. A chocolaty feast that stimulates your taste buds and satisfies you.",
            "ASIN": "B07FNXXBJB",
            "BestSellersRank": "#1,309 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#20 in Chocolate Bars",
            "Brand": "‎Cadbury",
            "CustomerReviews": "4.5 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n547 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.5 out of 5 rating",
            "DateFirstAvailable": "16 July 2018",
            "Form": "‎Bar",
            "GenericName": "Fuse Chocolate",
            "IngredientType": "‎Vegetarian",
            "Ingredients": "‎Centre (Peanuts + CrÃ¨me + Caramel) 72%* - Peanuts (19%*), hydrogenated vegetable fat, Sugar, Liquid Glucose, Milk solids, Cocoa solids, Invert sugar, Humectant (422), Edible salt, Emulsifiers (442, 476). CONTAINS ADDED FLAVOUR (NATURAL, NATURE IDENTICAL AND ARTIFICIAL (CARAMEL AND ETHYL VANILLIN) FLAVOURING SUBSTANCES). Hydrogenated Vegetable fats used - Contains Trans Fats. Allergen information - Contains Milk, Peanuts, Sulphites. Manufactured on equipment that also processes products containing wheat and soya.",
            "ItemDimensions ": "23 x 35 x 100 Millimeters",
            "Item Package Quantity": "‎1",
            "ItemWeight": "25 g",
            "Itempartnumber": "‎8901233031712",
            "Manufacturer": "Mondelez India Foods Pvt. Ltd.",
            "NetQuantity": "‎25.0 gram",
            "PackageInformation": "‎Pouch",
            "Price":"20",
            "ProductDimensions": "‎2.3 x 3.5 x 10 cm; 25 Grams",
            "Weight": "‎25 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nA delicious fusion of crunchy peanuts, sweet caramel and a creamy centre\n\n\n\n\nAll coated in smooth cadbury milk chocolate\n\n\n\n\nA chocolaty feast",
            "image": "https://m.media-amazon.com/images/I/61WuerAy7xS._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/61WuerAy7xS._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61CJP9U8bWS._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61v7jrYDs7S._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61CAVYY+oKS._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61c2CuPDxvS._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/617GVde5CnS._SL1500_.jpg"}],
            "reviewsCount": "547 ratings",
            "rating": "4.5",
            "itemDetailUrl": "https://www.amazon.in/dp/B07FNXXBJB",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B07FNXXBJB",
            "title": "Filter by\nDelivery\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nCadbury Fuse Chocolate, 25 g\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B098T82ZJF",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "0",
            "breadCrumbs": "",
            "delivery": "",
            "itemDetailUrl": "https://www.amazon.in/dp/B098T82ZJF",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B098T82ZJF",
            "title": "Chocolate More details"
        },
        {
            "asin": "B00XYAKRAQ",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "0",
            "breadCrumbs": "Grocery & Gourmet Foods›Sweets, Chocolate & Gum›Chocolate›Bars",
            "delivery": "",
            "desc": "Enjoy your favourite Cadbury dairy milk crackle chocolate. Go crazy with the luscious taste of rich, smooth and creamy classic milk chocolate with rice crispiest. Every bite is crispier with those little taste explosions in your mouth.",
            "ASIN": "B00XYAKRAQ",
            "BestSellersRank": "#900 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#12 in Chocolate Bars",
            "Brand": "‎Cadbury",
            "CustomerReviews": "4.5 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n1,073 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.5 out of 5 rating",
            "DateFirstAvailable": "1 January 2017",
            "Form": "‎Bar",
            "GenericName": "Dairy Milk Crackle Chocolate Bar",
            "IngredientType": "‎Vegetarian",
            "ItemDimensions ": "15.2 x 20.3 x 46.8 Centimeters",
            "Item Package Quantity": "‎1",
            "ItemWeight": "36 g",
            "Itempartnumber": "‎8901233018706 - For Pantry",
            "Manufacturer": "Mondelez India Foods Pvt. Ltd.",
            "NetQuantity": "‎1 count",
            "PackageInformation": "‎Pouch",
            "Price":"40",
            "ProductDimensions": "‎15.2 x 20.3 x 46.8 cm; 36 Grams",
            "Specialty": "‎Suitable for vegeterians",
            "Weight": "‎36 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nGo crazy with the luscious taste of crackle chocolate fortified with milk\n\n\n\n\nIt is an extremely rich taste chocolate with rice crispiest\n\n\n\n\nIt stands for goodness. A moment of pure magic",
            "image": "https://m.media-amazon.com/images/I/61vMDVz2bNL._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/61vMDVz2bNL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71JRho8F2SL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71TNkOYjHRL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71ghjB5dy7L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71FraQTHefL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71eKYdhFQdL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71AI-v4ocfL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71aU3lFp5JL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71aU3lFp5JL._SL1500_.jpg"}],
            "reviewsCount": "1,073 ratings",
            "rating": "4.5",
            "itemDetailUrl": "https://www.amazon.in/dp/B00XYAKRAQ",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B00XYAKRAQ",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nCadbury Dairy Milk Crackle Chocolate Bar, 36 g\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B07H6T16FS",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "22",
            "breadCrumbs": "Grocery & Gourmet Foods›Sweets, Chocolate & Gum›Chocolate›Bars",
            "delivery": "",
            "desc": "Crispello is a finger format chocolate with crispy centre, covered with a thin layer of delicious cadbury dairy milk. The crunchy and light crispy balls at the centre gives it a novel eat experience. The four finger format also makes it easy to share with friends and family.",
            "ASIN": "B07H6T16FS",
            "BestSellersRank": "#1,541 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#25 in Chocolate Bars",
            "Brand": "‎Cadbury",
            "CustomerReviews": "4.5 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n1,005 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.5 out of 5 rating",
            "DateFirstAvailable": "28 August 2018",
            "Form": "‎Ball",
            "GenericName": "Dairy Milk Crispello Chocolate Bar",
            "IngredientType": "‎Vegetarian",
            "ItemDimensions ": "12 x 5 x 1.3 Centimeters",
            "Item Package Quantity": "‎1",
            "ItemWeight": "35 g",
            "Itempartnumber": "‎31521",
            "Manufacturer": "Mondelez India Foods Pvt. Ltd.",
            "NetQuantity": "‎35.0 gram",
            "PackageInformation": "‎Pouch",
            "Price":"60",
            "ProductDimensions": "‎12 x 5 x 1.3 cm; 35 Grams",
            "Specialty": "‎Suitable for vegeterians",
            "Weight": "‎35 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nCrispello is a finger format chocolate with crispy centre, covered with a thin layer of delicious cadbury dairy milk\n\n\n\n\nIt has crunchy and light crispy balls at the centre covered in a smooth layer of cadbury dairy milk chocolate\n\n\n\n\nIt comes as 4 fingers which makes it easy to share with friends and family",
            "image": "https://m.media-amazon.com/images/I/61bjofxv25L._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/61bjofxv25L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61MDOpsPNnS._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71vMZ-GA7PL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61YRG1dkM7L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/613wROzS75L._SL1500_.jpg"}],
            "reviewsCount": "1,005 ratings",
            "rating": "4.5",
            "itemDetailUrl": "https://www.amazon.in/dp/B07H6T16FS",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B07H6T16FS",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nCadbury Dairy Milk Crispello Chocolate Bar, 35 g\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B00LOZWYPO",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "516",
            "breadCrumbs": "Grocery & Gourmet Foods›Jams, Honey & Spreads›Nut Butters",
            "delivery": "",
            "desc": "Size:350g\n\n\n\n\n\n | \n\nDesign:Hazelnut\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nThe unique taste of Nutella hazelnut spread continues to come from the combination of roasted hazelnuts, skim milk and a hint of cocoa. In addition, Nutella has no artificial colors or preservatives .",
            "ASIN": "B00LOZWYPO",
            "Allergen Information": "‎Dairy",
            "BestSellersRank": "#79 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#4 in Nut Butters",
            "Brand": "‎Nutella",
            "CountryOfOrigin": "‎Poland",
            "Cuisine": "‎English",
            "CustomerReviews": "4.5 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n29,100 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.5 out of 5 rating",
            "DateFirstAvailable": "1 January 2017",
            "GenericName": "Ferrero Chocolate Spread",
            "Importer": "Ferrero India pvt Ltd, MIDC, Plot F13, Baramati District, Pune, 413133, India customercare.india@ferrero.com 1800-209-1200",
            "IncludedComponents": "1 Nutella Jar",
            "IngredientType": "‎Vegetarian",
            "Ingredients": "‎SUGAR, PALM OIL, HAZELNUTS, SKIM MILK, COCOA, SOY LECITHIN AS EMULSIFIER, VANILLIN: AN ARTIFICIAL FLAVOR.",
            "ItemDimensions ": "10.6 x 9 x 8 Centimeters",
            "Item Package Quantity": "‎1",
            "ItemWeight": "380 g",
            "Item model number": "‎XGB623039",
            "Manufacturer": "Ferrero India, FERRERO POLSKA COMMERCIAL Sp. z o.o.. Siedziba firmy. Ul. Wiertnicza 126, 02-952 WARSZAWA Poland customercare.india@ferrero.com 1800-209-1200",
            "NetQuantity": "‎350.0 gram",
            "PackageInformation": "‎Jar",
            "Packer": "Ferrero India pvt Ltd, MIDC, Plot F13, Baramati District, Pune, 413133, India customercare.india@ferrero.com 1800-209-1200",
            "Price":"150",
            "ProductDimensions": "‎10.6 x 9 x 8.01 cm; 380 Grams",
            "Specialty": "‎Suitable for Vegetarians",
            "Storage Instructions": "‎Keep in a cool & dry place",
            "Weight": "‎0.38 Kilograms",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nIt's so delicious that a little goes a long way\n\n\n\n\nContains no artificial preservatives\n\n\n\n\nContains no artificial colors",
            "image": "https://m.media-amazon.com/images/I/714A58g3xWS._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/714A58g3xWS._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71mEMXbxZdL._SL1100_.jpg"},
            {image: "https://m.media-amazon.com/images/I/6152-uqBNES._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71roYVSeH8S._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61iXAzy0LwS._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/51bqeG3RFYS._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61UlWZh3jnS._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/91HAC-7pAGL._SL1500_.jpg"}],
            "reviewsCount": "29,100 ratings",
            "rating": "4.5",
            "itemDetailUrl": "https://www.amazon.in/dp/B00LOZWYPO",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B00LOZWYPO",
            "title": "Filter by\nDelivery\n\nCondition\n\n\n\n\n\n\n\n\n\nNutella Hazelnut Spread with Cocoa (Labels may vary), 350g\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B08GXJ9KV6",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "0",
            "breadCrumbs": "Grocery & Gourmet Foods›Sweets, Chocolate & Gum›Chocolate›Bars",
            "delivery": "",
            "desc": "Crunchy almonds and handpicked juicy raisins, studded in the smooth texture of dark chocolate. With 55% cocoa, Amul fruit 'n' Nut chocolate is a classic combination, celebrated for decades, relished even td.",
            "ASIN": "B08GXJ9KV6",
            "Allergen Information": "‎Nut",
            "BestSellersRank": "#1,028 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#15 in Chocolate Bars",
            "Brand": "‎Amul",
            "CountryOfOrigin": "‎India",
            "CustomerReviews": "4.6 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n813 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.6 out of 5 rating",
            "DateFirstAvailable": "11 February 2020",
            "Form": "‎Bar",
            "GenericName": "Fruit N Nut Chocolate",
            "Importer": "Kaira District Co-operative milk producers' Union Ltd.(A Unit of Kaira Dist. Co-op. Milk Producers’ Union Ltd.), Jibhaipura, Nadiad-Ahmedabad Road, Mehmedabad, Dist.: Kheda, Gujarat – 387 130.Lic. No. 10020021005504.",
            "IngredientType": "‎Vegetarian",
            "ItemDimensions ": "21 x 9 x 2 Centimeters",
            "Item Package Quantity": "‎1",
            "ItemWeight": "150 g",
            "Item model number": "‎AAK611",
            "Manufacturer": "GCMMF, Kaira District Co-operative milk producers' Union Ltd.(A Unit of Kaira Dist. Co-op. Milk Producers’ Union Ltd.), Jibhaipura, Nadiad-Ahmedabad Road, Mehmedabad, Dist.: Kheda, Gujarat – 387 130.Lic. No. 10020021005504.",
            "NetQuantity": "‎150.0 gram",
            "Packer": "Kaira District Co-operative milk producers' Union Ltd.(A Unit of Kaira Dist. Co-op. Milk Producers’ Union Ltd.), Jibhaipura, Nadiad-Ahmedabad Road, Mehmedabad, Dist.: Kheda, Gujarat – 387 130.Lic. No. 10020021005504.",
            "Price":"80",
            "ProductDimensions": "‎21 x 9 x 2 cm; 150 Grams",
            "Specialty": "‎Suitable for vegeterians",
            "Volume": "‎150 Millilitres",
            "Weight": "‎150 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nN Nut and\n\n\n\n\nno milk solids\n\n\n\n\nfull of raisins and almonds in 55% dark chocolate\n\n\n\n\nFruit N Nut Chocolate",
            "image": "https://m.media-amazon.com/images/I/71pvrI9XLyL._SL1500_.jpg",
            "images": [{ image: "https://m.media-amazon.com/images/I/71pvrI9XLyL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/7125x5NcU1L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61KuuYOpNyL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61MQbJ7NnpL._SL1500_.jpg"}],
            "reviewsCount": "813 ratings",
            "rating": "4.6",
            "itemDetailUrl": "https://www.amazon.in/dp/B08GXJ9KV6",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B08GXJ9KV6",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nAmul Fruit N Nut Chocolate, 150 g\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        },
        {
            "asin": "B08C2GNX2H",
            "currency": "INR",
            "InStock": "true",
            "NumberOfQuestions": "0",
            "breadCrumbs": "Grocery & Gourmet Foods›Sweets, Chocolate & Gum›Chocolate›Bars",
            "delivery": "",
            "desc": "Cadbury dairy milk chocolate is for those everyday moments of joy that you want to share with your near and dear ones with something sweet. Just one bite will take you into the world of warmth, happiness and spontaneous fun.",
            "ASIN": "B08C2GNX2H",
            "BestSellersRank": "#851 in Grocery & Gourmet Foods (See Top 100 in Grocery & Gourmet Foods)\n\n\n#11 in Chocolate Bars",
            "Brand": "‎Cadbury",
            "CustomerReviews": "4.5 out of 5 rating\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n1,015 ratings\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n4.5 out of 5 rating",
            "DateFirstAvailable": "30 June 2020",
            "Form": "‎Bar",
            "GenericName": "Dairy Milk Chocolate Bar",
            "IngredientType": "‎Vegetarian",
            "Ingredients": "‎Sugar, Milk Solids (22%*), Cocoa Butter, Cocoa Solids, Emulsifiers (442, 476). CONTAINS ADDED FLAVOUR (NATURAL, NATURE IDENTICAL AND ARTIFICIAL (ETHYL VANILLIN) FLAVOURING SUBSTANCES). Allergen Information: Contains Milk, Manufactured on equipment that also processes products containing tree nuts and wheat.",
            "ItemDimensions ": "41 x 99 x 7 Millimeters",
            "ItemWeight": "24 g",
            "Itempartnumber": "‎7622201149406_Fba",
            "Manufacturer": "Mondelez India Foods Pvt. Ltd., Mondelez India Foods Private Limited, Unit No. 2001, 20th Floor, Tower - 3, (Wing C), Indiabulls Finance Centre, Parel, Mumbai - 400 013.",
            "NetQuantity": "‎24.0 gram",
            "Price":"20",
            "ProductDimensions": "‎4.1 x 9.9 x 0.7 cm; 24 Grams",
            "Specialty": "‎Natural",
            "Weight": "‎24 Grams",
            "featureDesc": "This is a Vegetarian product.\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\n\n\n\n\n\n\n\n\nDelightfully rich, smooth and delicious chocolate with melt-in-the-mouth texture\n\n\n\n\nCadbury stands for goodness and a moment of pure magic!\n\n\n\n\nHurry up! Order now to experience the luscious taste of the classic Cadbury dairy milk chocolate bar",
            "image": "https://m.media-amazon.com/images/I/61rOyPund0L._SL1500_.jpg",
            "images" : [{ image: "https://m.media-amazon.com/images/I/61rOyPund0L._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61YLoie3tkL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71xKjuYx5NL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61rwdk19oRL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/71ybQJWNCgL._SL1500_.jpg"},
            {image: "https://m.media-amazon.com/images/I/61UA-qqxWlL._SL1500_.jpg"}],
            "reviewsCount": "1,015 ratings",
            "rating": "4.5",
            "itemDetailUrl": "https://www.amazon.in/dp/B08C2GNX2H",
            "sellerOffersUrl": "https://www.amazon.in/gp/offer-listing/B08C2GNX2H",
            "title": "Filter by\nDelivery\n\nCondition\nDidn't find what you were looking for?\n\n\n\n\n\n\n\n\nCadbury Dairy Milk Chocolate Bar, 24 g\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAbout this item\nTechnical DetailsAdditional Information\nFeedback"
        }
    ]

export default Chocolatedata;